services:
  - type: web
    name: network-automation
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    ports:
      - 8501
    healthCheckPath: /
    startCommand: "bash start.sh"
    envVars:
      - key: STREAMLIT_SERVER_HEADLESS
        value: "true"
